### ISSUE TITLE
How do we use this?

### ISSUE THREAD

**Issue by javorszky** [jacklenox/theming-react-and-the-rest-api#1]
Hiya,

Wanted to look at the slides, but not sure how to make it work. Cloned it, npm installed it, gulp is globally installed, react is globally installed. Errors out with:

```
javorszky at GaborrMBP in ~/Sites/j on git:master o [16:25:24]
$ gulp build-theme
[16:25:26] Using gulpfile ~/Sites/j/gulpfile.js
[16:25:26] Starting 'build-theme'...
[16:25:27] 'build-theme' errored after 113 ms
[16:25:27] ReferenceError: document is not defined
    at React.createClass.render (/Users/javorszky/Sites/j/transpiled/site/loop/index.js:17:3)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/javorszky/Sites/j/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (/Users/javorszky/Sites/j/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at wrapper [as _renderValidatedComponent] (/Users/javorszky/Sites/j/node_modules/react/lib/ReactPerf.js:70:21)
    at ReactCompositeComponentMixin.mountComponent (/Users/javorszky/Sites/j/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at wrapper [as mountComponent] (/Users/javorszky/Sites/j/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/javorszky/Sites/j/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/javorszky/Sites/j/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/javorszky/Sites/j/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/javorszky/Sites/j/node_modules/react/lib/ReactDOMComponent.js:199:12)
```

Would you be able to provide a readme?

**Comment by jacklenox** [comment]
Yep sorry, it's a pretty rough pass at this as I did it in a hurry.

You need to run `gulp transpile-js` before you run `gulp build-theme`. It all needs to be tidied up so that that happens automatically.
